# python3 train_net_clearml.py --clearml-proj PP_det2 --clearml-task-name june2021collated --clearml-task-type training  --docker-img harbor.dsta.ai/public/detectron2:v3 --queue 1gpu --num-gpus 1 --clearml-output-uri ${AWS_ENDPOINT_URL}/pixelplus-s3/model/snapshot/det2/ --s3-models-bucket pixelplus-s3 --s3-models-path model/ObjectDetection --s3-data-bucket pixelplus-s3 --s3-data-path data/ObjectDetection --s3-output-bucket pixelplus-s3 --s3-output-path model/snapshot/det2 --config-file configs/pp/clearml_faster_rcnn_R_50_FPN.yaml --model-weights faster_rcnn_R_50_FPN_3x/model_final_280758.pkl --output-dir ./output --datasets-train "('june2021collated_train',)" --datasets-test "('june2021collated_val',)" --download-data june2021collated  --test-eval-period 5000 --solver-ims-per-batch 4 --solver-base-lr 0.01 --solver-warmup-iters 5000 --solver-steps "(25000,50000)" --solver-max-iter 75000 --solver-checkpoint-period 5000 --noclearml

# python3 train_net_clearml.py --clearml-proj PP_det2 --clearml-task-name june2021collated --clearml-task-type training  --docker-img harbor.dsta.ai/public/detectron2:v3 --queue 1gpu --num-gpus 1 --clearml-output-uri ${AWS_ENDPOINT_URL}/pixelplus-s3/model/snapshot/det2/ --s3-models-bucket pixelplus-s3 --s3-models-path model/ObjectDetection --s3-data-bucket pixelplus-s3 --s3-data-path data/ObjectDetection --s3-output-bucket pixelplus-s3 --s3-output-path model/snapshot/det2 --config-file configs/pp/clearml_faster_rcnn_R_50_FPN.yaml --model-weights faster_rcnn_R_50_FPN_3x/model_final_280758.pkl --output-dir ./output --datasets-train "('june2021collated_train',)" --datasets-test "('june2021collated_val',)" --download-data june2021collated  --test-eval-period 5000 --solver-ims-per-batch 4 --solver-base-lr 0.01 --solver-warmup-iters 5000 --solver-steps "(25000,50000)" --solver-max-iter 75000 --solver-checkpoint-period 5000

# python3 train_net_clearml.py --clearml-proj PP_det2 --clearml-task-name june2021collated_IN --clearml-task-type training  --docker-img harbor.dsta.ai/public/detectron2:v3 --queue 1gpu --num-gpus 1 --clearml-output-uri ${AWS_ENDPOINT_URL}/pixelplus-s3/model/snapshot/det2/ --s3-models-bucket pixelplus-s3 --s3-models-path model/ObjectDetection --s3-data-bucket pixelplus-s3 --s3-data-path data/ObjectDetection --s3-output-bucket pixelplus-s3 --s3-output-path model/snapshot/det2 --config-file configs/pp/clearml_faster_rcnn_R_50_FPN_IN.yaml --model-weights faster_rcnn_R_50_FPN_3x/model_final_280758.pkl --output-dir ./output --datasets-train "('june2021collated_train',)" --datasets-test "('june2021collated_val',)" --download-data june2021collated  --test-eval-period 5000 --solver-ims-per-batch 4 --solver-base-lr 0.01 --solver-warmup-iters 5000 --solver-steps "(25000,50000)" --solver-max-iter 75000 --solver-checkpoint-period 5000

# python3 train_net_clearml.py --clearml-proj PP_det2 --clearml-task-name june2021collated_ptOct20 --clearml-task-type training  --docker-img harbor.dsta.ai/public/detectron2:v3 --queue 1gpu --num-gpus 1 --clearml-output-uri ${AWS_ENDPOINT_URL}/pixelplus-s3/model/snapshot/det2/ --s3-models-bucket pixelplus-s3 --s3-models-path model/ObjectDetection --s3-data-bucket pixelplus-s3 --s3-data-path data/ObjectDetection --s3-output-bucket pixelplus-s3 --s3-output-path model/snapshot/det2 --config-file configs/pp/clearml_faster_rcnn_R_50_FPN.yaml --model-weights oct2020SV_model_from0039999/model_0034999_best.pth --output-dir ./output --datasets-train "('june2021collated_train',)" --datasets-test "('june2021collated_val',)" --download-data june2021collated  --test-eval-period 5000 --solver-ims-per-batch 4 --solver-base-lr 0.01 --solver-warmup-iters 5000 --solver-steps "(25000,50000)" --solver-max-iter 75000 --solver-checkpoint-period 5000

python3 train_net_clearml.py --clearml-proj PP_det2 --clearml-task-name june2021collated_IN_ptOct20IN --clearml-task-type training  --docker-img harbor.dsta.ai/public/detectron2:v3 --queue 1gpu --num-gpus 1 --clearml-output-uri ${AWS_ENDPOINT_URL}/pixelplus-s3/model/snapshot/det2/ --s3-models-bucket pixelplus-s3 --s3-models-path model/ObjectDetection --s3-data-bucket pixelplus-s3 --s3-data-path data/ObjectDetection --s3-output-bucket pixelplus-s3 --s3-output-path model/snapshot/det2 --config-file configs/pp/clearml_faster_rcnn_R_50_FPN_IN.yaml --model-weights oct2020SV_model_withIN/model_0064999_best.pth --output-dir ./output --datasets-train "('june2021collated_train',)" --datasets-test "('june2021collated_val',)" --download-data june2021collated  --test-eval-period 5000 --solver-ims-per-batch 4 --solver-base-lr 0.01 --solver-warmup-iters 5000 --solver-steps "(25000,50000)" --solver-max-iter 75000 --solver-checkpoint-period 5000
